#!/usr/bin/env python3
#
# Pardus Flatpak GUI main exectuable script (new)
# Copyright (C) 2020 Erdem Ersoy
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from pardusflatpakgui.flatpakguiapp import FlatpakGUIApp

import sys
import gi
gi.require_version('Gio', '2.0')
from gi.repository import Gio


def main():
    app = FlatpakGUIApp("tr.org.pardus.pardus-flatpak-gui",
                        Gio.ApplicationFlags.FLAGS_NONE)
    return app.run()


if __name__ == "__main__":
    exit_status = main()
    sys.exit(exit_status)
